### PR TITLE
fix termui breakage

### LINKED ISSUE #661: module 'click.termui' has no attribute 'get_terminal_size'
I am getting this error when uploading a folder to bucket with prefix.

command
```bash
oci os object bulk-upload --src-dir folder -bn bucket-name --prefix "folder/"
```

message
```json
{
  "skipped-objects": [],
  "upload-failures": {
    "folder/newFile": "module 'click.termui' has no attribute 'get_terminal_size'"
  },
  "uploaded-objects": {}
}
```

operating system: `arch linux 6.2.9-arch1-1`
`oci-cli` version: `3.25.1-1`
`python-click` version: `8.1.3-1`

### PR DESCRIPTION
**Pull request by dch**
- https://github.com/oracle/oci-cli/issues/661
- https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-0 closes #661

### CODE REVIEW

**Comment by dch** [comment]
cf downstream https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271891

**Comment by miteshsavani810** [comment]
Please merge this. This is really blocker to use 'bulk-upload' utility.

**Comment by seahl0119** [comment]
Please merge this. This is really hinder me to using 'bulk-upload' utility.

**Comment by Kanvipasricha** [comment]
OCI CLI team is verifying the changes and will release a fix at the earliest possible.

**Review by Kanvipasricha — APPROVED** [review]

**Pull request merged**
