### PR TITLE
Add '--content-type auto' flag for object storage put/bulk-upload

### PR DESCRIPTION
**Pull request by rosalexander**
Currently, we have to manually specify the content type of files we upload to an object storage bucket. This can become tedious when we do a bulk-upload because the content-type flag will upload all the files with the same content-type regardless of whether it is accurate. I propose using the mimetypes standard library in Python  and adding a '--content-type auto' flag when using object storage bulk-upload and put commands to automatically generate the content-type for each file. Apologies if a feature like this has been considered already. Thank you!

Signed-off-by: Alexander Ros <alexander.ros@oracle.com>

### CODE REVIEW

**Comment by paul-hummel-oracle** [comment]
Hi @rosalexander, This looks like a useful and helpful contribution!

I would like to have a test written for the change as well. Can you do that?
If not, that's ok, I've opened an internal ticket for us to try this out and test.

We are going to be moving our integration tests for object storage to https://github.com/oracle/oci-cli/tree/master/services/object_storage/tests/integ.
But for now, they still reside under https://github.com/oracle/oci-cli/tree/master/tests.


thank you,
paul

**Comment by rosalexander** [comment]
Hi @paul-hummel-oracle,

Thank you for the response! I'll see if I can do about the tests. I'm not sure if its my tenancy or environment, but I'm failing a couple of the object storage pytests on the master branch. Also, I was attempting to write some tests with the 'oci os object list' commands but I don't believe it returns the content type of objects to do some asserts.

Best regards,
Alexander Ros

**Comment by paul-hummel-oracle** [comment]
No worries, regarding the automated tests -- we could definitely pick that up when we try this out.

**Comment by paul-hummel-oracle** [comment]
@rosalexander FYI, we have a dev working with your pull request now and adding some tests.

**Comment by rosalexander** [comment]
Thanks for the update @paul-hummel-oracle! Let me know if theres anything I could do

**Comment by srikanthkumbham** [comment]
@rosalexander Your changes have been included in the latest release(2.5.8). Ref: https://github.com/oracle/oci-cli/releases/tag/v2.5.8

You can now close this pull request. Thanks for your contribution! :)

**Pull request closed without merging**
